import pdb

import os
import torch
import torch.nn as nn
from functools import reduce


class LambdaBase(nn.Sequential):
    def __init__(self, fn, *args):
        super(LambdaBase, self).__init__(*args)
        self.lambda_func = fn

    def forward_prepare(self, input):
        output = []
        for module in self._modules.values():
            output.append(module(input))
        return output if output else input


class Lambda(LambdaBase):
    def forward(self, input):
        return self.lambda_func(self.forward_prepare(input))


class LambdaMap(LambdaBase):
    def forward(self, input):
        return list(map(self.lambda_func, self.forward_prepare(input)))


class LambdaReduce(LambdaBase):
    def forward(self, input):
        return reduce(self.lambda_func, self.forward_prepare(input))


DIW_scratch = nn.Sequential(  # Sequential,
    nn.Conv2d(3, 128, (7, 7), (1, 1), (3, 3)),
    nn.BatchNorm2d(128),
    nn.ReLU(),
    nn.Sequential(  # Sequential,
        LambdaMap(
            lambda x: x,  # ConcatTable,
            nn.Sequential(  # Sequential,
                nn.MaxPool2d((2, 2), (2, 2)),
                LambdaReduce(
                    lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                ),
                LambdaReduce(
                    lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                ),
                nn.Sequential(  # Sequential,
                    LambdaMap(
                        lambda x: x,  # ConcatTable,
                        nn.Sequential(  # Sequential,
                            nn.MaxPool2d((2, 2), (2, 2)),
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 64, (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                            nn.Sequential(  # Sequential,
                                LambdaMap(
                                    lambda x: x,  # ConcatTable,
                                    nn.Sequential(  # Sequential,
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                    ),
                                    nn.Sequential(  # Sequential,
                                        nn.AvgPool2d((2, 2), (2, 2)),
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                        nn.Sequential(  # Sequential,
                                            LambdaMap(
                                                lambda x: x,  # ConcatTable,
                                                nn.Sequential(  # Sequential,
                                                    LambdaReduce(
                                                        lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 64, (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                    ),
                                                    LambdaReduce(
                                                        lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 64, (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                    ),
                                                ),
                                                nn.Sequential(  # Sequential,
                                                    nn.AvgPool2d((2, 2), (2, 2)),
                                                    LambdaReduce(
                                                        lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 64, (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                    ),
                                                    LambdaReduce(
                                                        lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 64, (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                    ),
                                                    LambdaReduce(
                                                        lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 64, (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                        nn.Sequential(  # Sequential,
                                                            nn.Conv2d(256, 32, (1, 1)),
                                                            nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                            nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                            nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                            nn.ReLU(),
                                                        ),
                                                    ),
                                                    nn.UpsamplingNearest2d(scale_factor=2),
                                                ),
                                            ),
                                            LambdaReduce(lambda x, y: x + y),  # CAddTable,
                                        ),
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 32, (1, 1)),
                                                nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                        LambdaReduce(
                                            lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (3, 3), (1, 1), (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (7, 7), (1, 1), (3, 3)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                            nn.Sequential(  # Sequential,
                                                nn.Conv2d(256, 64, (1, 1)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                                nn.Conv2d(64, 64, (11, 11), (1, 1), (5, 5)),
                                                nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                                nn.ReLU(),
                                            ),
                                        ),
                                        nn.UpsamplingNearest2d(scale_factor=2),
                                    ),
                                ),
                                LambdaReduce(lambda x, y: x + y),  # CAddTable,
                            ),
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 64, (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (5, 5), (1, 1), (2, 2)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 64, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(256, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                            nn.UpsamplingNearest2d(scale_factor=2),
                        ),
                        nn.Sequential(  # Sequential,
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (5, 5), (1, 1), (2, 2)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(32, 32, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                            LambdaReduce(
                                lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 32, (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 64, (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 64, (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                                nn.Sequential(  # Sequential,
                                    nn.Conv2d(128, 64, (1, 1)),
                                    nn.BatchNorm2d(64, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                    nn.Conv2d(64, 32, (11, 11), (1, 1), (5, 5)),
                                    nn.BatchNorm2d(32, 1e-05, 0.1, False),
                                    nn.ReLU(),
                                ),
                            ),
                        ),
                    ),
                    LambdaReduce(lambda x, y: x + y),  # CAddTable,
                ),
                LambdaReduce(
                    lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 32, (3, 3), (1, 1), (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 32, (5, 5), (1, 1), (2, 2)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 32, (7, 7), (1, 1), (3, 3)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                ),
                LambdaReduce(
                    lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 16, (1, 1)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 16, (3, 3), (1, 1), (1, 1)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 16, (7, 7), (1, 1), (3, 3)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 32, (1, 1)),
                        nn.BatchNorm2d(32, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(32, 16, (11, 11), (1, 1), (5, 5)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                ),
                nn.UpsamplingNearest2d(scale_factor=2),
            ),
            nn.Sequential(  # Sequential,
                LambdaReduce(
                    lambda x, y, dim=1: torch.cat((x, y), dim),  # Concat,
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 16, (1, 1)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 16, (3, 3), (1, 1), (1, 1)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 16, (7, 7), (1, 1), (3, 3)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                    nn.Sequential(  # Sequential,
                        nn.Conv2d(128, 64, (1, 1)),
                        nn.BatchNorm2d(64, 1e-05, 0.1, False),
                        nn.ReLU(),
                        nn.Conv2d(64, 16, (11, 11), (1, 1), (5, 5)),
                        nn.BatchNorm2d(16, 1e-05, 0.1, False),
                        nn.ReLU(),
                    ),
                ),
            ),
        ),
        LambdaReduce(lambda x, y: x + y),  # CAddTable,
    ),
    nn.Conv2d(64, 1, (3, 3), (1, 1), (1, 1)),
)


def load_weight(model, path, prefix=None):
    """Load model."""

    if not os.path.exists(path):
        raise IOError(f"Model checkpoint '{path}' doesn't exist.")

    # state_dict = torch.load(path, map_location=lambda storage, loc: storage)
    state_dict = torch.load(path, map_location=torch.device("cpu"))

    target_state_dict = model.state_dict()
    if prefix is not None and isinstance(prefix, str):
        for n, p in state_dict.items():
            n = n.replace(prefix, "")
            if n in target_state_dict.keys():
                target_state_dict[n].copy_(p)
            else:
                raise KeyError(n)
    else:
        for n, p in state_dict.items():
            if n in target_state_dict.keys():
                target_state_dict[n].copy_(p)
            else:
                raise KeyError(n)


class MegaDepthModel(nn.Module):
    """MegaDepth Hour Glass Model"""

    def __init__(self):
        super(MegaDepthModel, self).__init__()
        self.MAX_H = 1024
        self.MAX_W = 2048
        self.MAX_TIMES = 16
        # GPU 6G, 660ms

        self.netG = DIW_scratch

        self.load_weights()

    def load_weights(self, model_path="models/image_depth.pth"):
        cdir = os.path.dirname(__file__)
        checkpoint = model_path if cdir == "" else cdir + "/" + model_path
        if os.path.exists(checkpoint):
            load_weight(self.netG, checkpoint, prefix="module.")

    def forward(self, x):
        pred_log_depth = self.netG(x)
        y = 1.0/torch.exp(pred_log_depth)
        y = y/y.max()
        return y
